version: "3.9"
services:
  # Admin
  admin:
    container_name: admin_container
    build: ./admin
    ports:
      - "3006:3000"
    env_file:
      - ./admin/.env
    depends_on:
      - mongo
      - server
    volumes:
      - ./admin:/user/src/app:ro
      - /user/src/app/node_modules
  # Client
  client:
    container_name: client_container
    build: ./client
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env
    depends_on:
      - mongo
      - server
    volumes:
      - ./client:/user/src/app:ro
      - /user/src/app/node_modules
  # Server
  server:
    container_name: server_container
    build: ./server
    ports:
      - "4000:4000"
    env_file:
      - ./server/.env
    depends_on:
      - mongo
    volumes:
      - ./server:/user/src/app:ro
      - /user/src/app/node_modules
  # MOngoDB
  mongo:
    container_name: mongo_container
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db

volumes:
  mongo_db: {}
